2022 (1)
==========

* Schürz M, Danmayr J, Jaritsch M, Klinglmayr E, Benirschke HM, Matea CT, Zimmerebner P, Rauter J, Wolf M, Gomes FG, Kratochvil Z, Heger Z, Miller A, Heuser T, Stanojlovic V, Kiefer J, Plank T, Johnson L, Himly M, Blöchl C, Huber CG, Hintersteiner M, Meisner-Kober N. EVAnalyzer: High content imaging for rigorous characterisation of single extracellular vesicles using standard laboratory equipment and a new open-source ImageJ/Fiji plugin. J Extracell Vesicles. 2022 Dec;11(12):e12282. doi: 10.1002/jev2.12282. PMID: 36437554; PMCID: PMC9702573. 📗